### ISSUE TITLE
MFP-related settings required even if MFP is not used

### ISSUE THREAD

**Issue by pfirpfel** [openoereb/pyramid_oereb#873]
Currently, the yaml-configuration must contain these PDF print properties, otherwise pyramid_oereb will not produce a JSON/XML extract (even if the PDF print is not used):

```yaml
print:
    buffer: 30
    basic_map_size: [493, 280]
    pdf_dpi: 300
    pdf_map_size_millimeters: [174, 99]
```

All these are used in [pyramid_oereb/lib/records/view_service.py](https://github.com/openoereb/pyramid_oereb/blob/master/pyramid_oereb/lib/records/view_service.py).

There is some analysis needed to determine how to refactor this the best way.

Current workaround is just to have these properties defined in the configuration.
